# Generated by Django 5.1.1 on 2024-10-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_query_cart_item_cartitem_cart_items_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Xlarge'), ('xxlarge', 'XXlarge')], max_length=15, null=True),
        ),
    ]
