# Generated by Django 5.1.1 on 2024-11-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Jaipur', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Bharat', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='Rajasthan', max_length=30),
        ),
    ]
