# Generated by Django 5.1.5 on 2025-01-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_userprofile_city_userprofile_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="gender",
            field=models.CharField(
                choices=[
                    ("men", "Men"),
                    ("women", "Women"),
                    ("girls", "Girls"),
                    ("boys", "Boys"),
                    ("all", "All"),
                ],
                default="all",
                max_length=10,
            ),
        ),
    ]
